In [ ]:
# **2.4 Preliminary Steps - Predicting Home Values In The West Roxbury Neighborhood**

In [1]:
# *Loading And Looking At The Data In Python - TABLE 2.3*

# Import required packages.
import pandas as pd

In [3]:
# Load required data.
housing_df = pd.read_csv(r'Course Data\dmba\WestRoxbury.csv')

In [4]:
# Find the dimensions of the data frame.
housing_df.shape

(5802, 14)

In [5]:
# Show the first five rows of the data frame.
housing_df.head()

,TOTAL VALUE,TAX,LOT SQFT,YR BUILT,GROSS AREA,LIVING AREA,FLOORS,ROOMS,BEDROOMS,FULL BATH,HALF BATH,KITCHEN,FIREPLACE,REMODEL
0,344.2,4330,9965,1880,2436,1352,2.0,6,3,1,1,1,0,NaN
1,412.6,5190,6590,1945,3108,1976,2.0,10,4,2,1,1,0,Recent
2,330.1,4152,7500,1890,2294,1371,2.0,8,4,1,1,1,0,NaN
3,498.6,6272,13773,1957,5032,2608,1.0,9,5,1,1,1,1,NaN
4,331.5,4170,5000,1910,2370,1438,2.0,7,3,2,0,1,0,NaN

In [6]:
# Rename columns: replace spaces with '_' to allow dot notation.
#housing_df = housing_df.rename(columns={'TOTAL VALUE ': 'TOTAL_VALUE'}) # explicit
housing_df.columns = [s.strip().replace(' ', '_') for s in housing_df.columns] # all columns

In [7]:
# Show the first four rows of the data frame to verify previous change.
housing_df.loc[0:3]  # loc[a:b] gives rows a to b, inclusive
#housing_df.iloc[0:4]  # iloc[a:b] gives rows a to b-1

,TOTAL_VALUE,TAX,LOT_SQFT,YR_BUILT,GROSS_AREA,LIVING_AREA,FLOORS,ROOMS,BEDROOMS,FULL_BATH,HALF_BATH,KITCHEN,FIREPLACE,REMODEL
0,344.2,4330,9965,1880,2436,1352,2.0,6,3,1,1,1,0,NaN
1,412.6,5190,6590,1945,3108,1976,2.0,10,4,2,1,1,0,Recent
2,330.1,4152,7500,1890,2294,1371,2.0,8,4,1,1,1,0,NaN
3,498.6,6272,13773,1957,5032,2608,1.0,9,5,1,1,1,1,NaN

In [8]:
# Show the first 10 values in the column TOTAL_VALUE.
#housing_df['TOTAL_VALUE'].iloc[0:10]
#housing_df.iloc[0:10]['TOTAL_VALUE']
housing_df.iloc[0:10].TOTAL_VALUE  # use dot notation if the column name has no spaces

0    344.2
1    412.6
2    330.1
3    498.6
4    331.5
5    337.4
6    359.4
7    320.4
8    333.5
9    409.4
Name: TOTAL_VALUE, dtype: float64

In [9]:
# Show the fifth row of the first 10 columns in the data frame.
#housing_df.iloc[4][0:10]
#housing_df.iloc[4, 0:10]
housing_df.iloc[4:5, 0:10]  # use a slice to return a data frame

,TOTAL_VALUE,TAX,LOT_SQFT,YR_BUILT,GROSS_AREA,LIVING_AREA,FLOORS,ROOMS,BEDROOMS,FULL_BATH
4,331.5,4170,5000,1910,2370,1438,2.0,7,3,2

In [10]:
# Use pd.concat to combine non-consecutive columns into a new data frame.
# The axis argument specifies the dimension along which the concatenation happens, 0=rows, 1=columns.
pd.concat([housing_df.iloc[4:6,0:2], housing_df.iloc[4:6,4:6]], axis=1)

   TOTAL_VALUE   TAX  GROSS_AREA  LIVING_AREA
4        331.5  4170        2370         1438
5        337.4  4244        2124         1060

In [11]:
# To specify a full column, use:
#housing_df.iloc[:,0:1]
housing_df.TOTAL_VALUE
#housing_df['TOTAL_VALUE'][0:10]  # show the first 10 rows of the first column

0       344.2
1       412.6
2       330.1
3       498.6
4       331.5
        ...
5797    404.8
5798    407.9
5799    406.5
5800    308.7
5801    447.6
Name: TOTAL_VALUE, Length: 5802, dtype: float64

In [12]:
# Descriptive statistics:
print('Number of rows ', len(housing_df['TOTAL_VALUE'])) # show length of first column
print('Mean of TOTAL_VALUE ', housing_df['TOTAL_VALUE'].mean()) # show mean of column
housing_df.describe() # show summary statistics for each column

Number of rows  5802
Mean of TOTAL_VALUE  392.6857149258877

,TOTAL_VALUE,TAX,LOT_SQFT,YR_BUILT,GROSS_AREA,LIVING_AREA,FLOORS,ROOMS,BEDROOMS,FULL_BATH,HALF_BATH,KITCHEN,FIREPLACE
count,5802.000000,5802.000000,5802.000000,5802.000000,5802.000000,5802.000000,5802.000000,5802.000000,5802.000000,5802.000000,5802.000000,5802.00000,5802.000000
mean,392.685715,4939.485867,6278.083764,1936.744916,2924.842123,1657.065322,1.683730,6.994829,3.230093,1.296794,0.613926,1.01534,0.739917
std,99.177414,1247.649118,2669.707974,35.989910,883.984726,540.456726,0.444884,1.437657,0.846607,0.522040,0.533839,0.12291,0.565108
min,105.000000,1320.000000,997.000000,0.000000,821.000000,504.000000,1.000000,3.000000,1.000000,1.000000,0.000000,1.00000,0.000000
25%,325.125000,4089.500000,4772.000000,1920.000000,2347.000000,1308.000000,1.000000,6.000000,3.000000,1.000000,0.000000,1.00000,0.000000
50%,375.900000,4728.000000,5683.000000,1935.000000,2700.000000,1548.500000,2.000000,7.000000,3.000000,1.000000,1.000000,1.00000,1.000000
75%,438.775000,5519.500000,7022.250000,1955.000000,3239.000000,1873.750000,2.000000,8.000000,4.000000,2.000000,1.000000,1.00000,1.000000
max,1217.800000,15319.000000,46411.000000,2011.000000,8154.000000,5289.000000,3.000000,14.000000,9.000000,5.000000,3.000000,2.00000,4.000000

In [14]:
# Import additional required packages.
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score
from sklearn.linear_model import LinearRegression

In [15]:
# *Sampling From A Database - TABLE 2.4*

# Random sample of 10 observations.
housing_df.sample(10)

# Oversample houses with over 10 rooms.
weights = [0.9 if rooms > 10 else 0.01 for rooms in housing_df.ROOMS]
housing_df.sample(10, weights=weights)

,TOTAL_VALUE,TAX,LOT_SQFT,YR_BUILT,GROSS_AREA,LIVING_AREA,FLOORS,ROOMS,BEDROOMS,FULL_BATH,HALF_BATH,KITCHEN,FIREPLACE,REMODEL
4151,996.9,12541,10050,2006,5392,4375,2.0,11,4,4,0,1,1,NaN
5281,460.2,5789,6900,1920,3570,2086,2.0,12,5,2,1,1,1,NaN
198,287.8,3620,6750,1956,2060,960,1.0,6,3,1,0,1,1,NaN
2687,397.1,4995,5000,1910,3014,1878,2.0,11,6,2,0,1,1,NaN
4844,672.6,8461,14282,1880,5062,2822,2.0,11,5,1,2,1,2,NaN
5338,427.4,5376,4739,1994,2613,2019,2.0,12,4,2,1,1,1,NaN
2141,566.6,7127,8369,1932,4163,2612,2.0,11,4,2,1,1,1,Recent
5156,421.2,5298,6190,1950,3165,1447,1.0,7,3,2,0,1,1,NaN
1578,496.1,6240,9858,1952,4612,2038,1.0,12,5,3,0,2,2,NaN
4693,389.1,4894,6483,1938,2642,1562,2.0,7,3,1,1,1,1,NaN

In [ ]:
# **Preprocessing And Cleaning The Data**

In [16]:
# *Reviewing Variables - TABLE 2.5*

# Print a list of variables.
housing_df.columns

Index(['TOTAL_VALUE', 'TAX', 'LOT_SQFT', 'YR_BUILT', 'GROSS_AREA',
       'LIVING_AREA', 'FLOORS', 'ROOMS', 'BEDROOMS', 'FULL_BATH', 'HALF_BATH',
       'KITCHEN', 'FIREPLACE', 'REMODEL'],
      dtype='object')

In [23]:
# REMODEL needs to be converted to a categorical variable.
housing_df.REMODEL = housing_df.REMODEL.astype('category')
#housing_df.REMODEL.cat.categories # show number of categories
housing_df.REMODEL.dtype # check type of converted variable

CategoricalDtype(categories=['Old', 'Recent'], ordered=False, categories_dtype=object)

In [27]:
# *Creating Dummy Variables - TABLE 2.6*

# Use drop_first=True to drop the first dummy variable, REMODEL_Old.
housing_df = pd.get_dummies(housing_df, prefix_sep='_', drop_first=True)
housing_df.columns

Index(['TOTAL_VALUE', 'TAX', 'LOT_SQFT', 'YR_BUILT', 'GROSS_AREA',
       'LIVING_AREA', 'FLOORS', 'ROOMS', 'BEDROOMS', 'FULL_BATH', 'HALF_BATH',
       'KITCHEN', 'FIREPLACE', 'REMODEL_Recent'],
      dtype='object')

In [28]:
# *Missing Data - TABLE 2.7*

# To illustrate missing data procedures, we first convert a few entries for bedrooms to NA's,
# then we impute these missing values using the median of the remaining values.
missingRows = housing_df.sample(10).index
housing_df.loc[missingRows, 'BEDROOMS'] = np.nan
print('Number of rows with valid BEDROOMS values after setting to NAN: ',
       housing_df['BEDROOMS'].count())

Number of rows with valid BEDROOMS values after setting to NAN:  5792

In [29]:
# Remove rows with missing values.
reduced_df = housing_df.dropna()
print('Number of rows after removing rows with missing values: ', len(reduced_df))

Number of rows after removing rows with missing values:  5792

In [30]:
# Replace the missing values using the median of the remaining values.
medianBedrooms = housing_df['BEDROOMS'].median()
housing_df.BEDROOMS = housing_df.BEDROOMS.fillna(value=medianBedrooms)
print('Number of rows with valid BEDROOMS values after filling NA values: ',
       housing_df['BEDROOMS'].count())

Number of rows with valid BEDROOMS values after filling NA values:  5802

In [31]:
# REMODEL_Recent needs to be converted from a boolean to a binary variable.
housing_df.REMODEL_Recent = housing_df.REMODEL_Recent.astype(int)
housing_df.REMODEL_Recent  # show number of categories

0       0
1       1
2       0
3       0
4       0
       ..
5797    1
5798    0
5799    0
5800    0
5801    0
Name: REMODEL_Recent, Length: 5802, dtype: int32

In [33]:
# *Normalizing And Rescaling Data - TABLE 2.8*

from sklearn.preprocessing import MinMaxScaler, StandardScaler
df = housing_df.copy()

# Normalizing a data frame.

# pandas:
norm_df = (housing_df - housing_df.mean()) / housing_df.std()

# scikit-learn:
scaler = StandardScaler()
norm_df = pd.DataFrame(scaler.fit_transform(housing_df),
                       index=housing_df.index, columns=housing_df.columns)

# The result of the transformation is a numpy array, we convert it into a dataframe.

# Rescaling a data frame.

# pandas:
norm_df = (housing_df - housing_df.min()) / (housing_df.max() - housing_df.min())

# scikit-learn:
scaler = MinMaxScaler()
norm_df = pd.DataFrame(scaler.fit_transform(housing_df),
                       index=housing_df.index, columns=housing_df.columns)

In [ ]:
# ***2.5 Predictive Power And Overfitting - Predicting Home Values In The West Roxbury Neighborhood***

In [ ]:
# **Creation And Use Of Data Partitions**

In [34]:
# *Data Partitioning - TABLE 2.10*

# Random_state is set to a defined value to get the same partitions when re-running the code.

# Training (60%) and Validation (40%)
trainData, validData = train_test_split(housing_df, test_size=0.40, random_state=10)

print('Training : ', trainData.shape)
print('Validation : ', validData.shape)
print()

# Training (50%), Validation (30%), and Test (20%)
trainData, temp = train_test_split(housing_df, test_size=0.5, random_state=10)
validData, testData = train_test_split(temp, test_size=0.4, random_state=10)

print('Training   : ', trainData.shape)
print('Validation : ', validData.shape)
print('Test       : ', testData.shape)

Training :  (3481, 14)
Validation :  (2321, 14)

Training   :  (2901, 14)
Validation :  (1740, 14)
Test       :  (1161, 14)

In [ ]:
# ***2.6 Building A Predictive Model - Predicting Home Values In The West Roxbury Neighborhood***

In [ ]:
# **Modeling Process**

In [35]:
# *Predictions (Fitted Values) For A Sample Of Training Data - TABLE 2.12*

from sklearn.linear_model import LinearRegression

# Data loading and preprocessing.
housing_df = pd.read_csv(r'Course Data\dmba\WestRoxbury.csv')
housing_df.columns = [s.strip().replace(' ', '_') for s in housing_df.columns]
housing_df = pd.get_dummies(housing_df, prefix_sep='_', drop_first=True)
 
# Create list of predictors and outcome.
excludeColumns = ('TOTAL_VALUE', 'TAX')
predictors = [s for s in housing_df.columns if s not in excludeColumns]
outcome = 'TOTAL_VALUE'
 
# Partition data.
X = housing_df[predictors]
y = housing_df[outcome]
train_X, valid_X, train_y, valid_y = train_test_split(X, y, test_size=0.4, random_state=1)

model = LinearRegression()
model.fit(train_X, train_y)

train_pred = model.predict(train_X)
train_results = pd.DataFrame({
'TOTAL_VALUE': train_y,
'predicted': train_pred,
'residual': train_y - train_pred
})
train_results.head()

      TOTAL_VALUE   predicted   residual
2024        392.0  388.204648   3.795352
5140        476.3  430.707903  45.592097
5259        367.4  384.572908 -17.172908
421         350.3  369.819105 -19.519105
1401        348.1  310.493153  37.606847

In [36]:
# *Predictions For A Sample Of Validation Data - TABLE 2.13*

valid_pred = model.predict(valid_X)
valid_results = pd.DataFrame({
    'TOTAL_VALUE': valid_y,
    'predicted': valid_pred,
    'residual': valid_y - valid_pred
})
valid_results.head()

      TOTAL_VALUE   predicted   residual
1822        462.0  407.428545  54.571455
1998        370.4  363.418289   6.981711
5126        407.4  390.743753  16.656247
808         316.1  383.045464 -66.945464
4034        393.2  434.999519 -41.799519

In [37]:
# *Prediction Error Metrics For Training And Validation Data - TABLE 2.14*

# Import the utility function regressionSummary.
from dmba import regressionSummary

# Evaluate training set.
regressionSummary(train_results.TOTAL_VALUE, train_results.predicted)

# Evaluate validation set.
regressionSummary(valid_results.TOTAL_VALUE, valid_results.predicted)

Regression statistics

                      Mean Error (ME) : 0.0000
       Root Mean Squared Error (RMSE) : 43.0511
            Mean Absolute Error (MAE) : 32.6190
          Mean Percentage Error (MPE) : -1.1127
Mean Absolute Percentage Error (MAPE) : 8.4921

Regression statistics

                      Mean Error (ME) : -0.0996
       Root Mean Squared Error (RMSE) : 42.7372
            Mean Absolute Error (MAE) : 31.9495
          Mean Percentage Error (MPE) : -1.0815
Mean Absolute Percentage Error (MAPE) : 8.3228

In [ ]:
# ***2.7 Using Python For Data Mining On A Local Machine - Predicting Home Values In The West Roxbury Neighborhood***

In [38]:
# *Data Frame With Three Records To Be Scored - TABLE 2.15*

new_data = pd.DataFrame({
    'LOT_SQFT': [4200, 6444, 5035],
    'YR_BUILT': [1960, 1940, 1925],
    'GROSS_AREA': [2670, 2886, 3264],
    'LIVING_AREA': [1710, 1474, 1523],
    'FLOORS': [2.0, 1.5, 1.9],
    'ROOMS': [10, 6, 6],
    'BEDROOMS': [4, 3, 2],
    'FULL_BATH': [1, 1, 1],
    'HALF_BATH': [1, 1, 0],
    'KITCHEN': [1, 1, 1],
    'FIREPLACE': [1, 1, 0],
    'REMODEL_Recent': [0, 0, 1],
})
print(new_data)
print('Predictions: ', model.predict(new_data))

   LOT_SQFT  YR_BUILT  GROSS_AREA  LIVING_AREA  FLOORS  ROOMS  BEDROOMS  \
0      4200      1960        2670         1710     2.0     10         4
1      6444      1940        2886         1474     1.5      6         3
2      5035      1925        3264         1523     1.9      6         2

   FULL_BATH  HALF_BATH  KITCHEN  FIREPLACE  REMODEL_Recent
0          1          1        1          1               0
1          1          1        1          1               0
2          1          0        1          0               1
Predictions:  [384.93232682 378.52367666 386.0838147 ]